# Generated by Django 4.0 on 2021-12-10 20:43

from django.db import migrations, models
import django.db.models.deletion
import post.current_user


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=post.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
